#!/usr/bin/env bash

if [ ! -f "build.sbt" ]; then
    echo "Error: No 'build.sbt' detected"
    exit1
fi

if [ ! -f "sim.cpp" ]; then
    echo "Error: No 'sim.cpp' detected"
    exit 1
fi

riscv32-none-elf-as -march=rv32i -mabi=ilp32 examples/without_thforce.asm -o generated/without_thforce.o
riscv32-none-elf-ld -T link.ld generated/without_thforce.o -o generated/without_thforce.elf
riscv32-none-elf-objcopy -O verilog --verilog-data-width=4 generated/without_thforce.elf generated/without_thforce.hex

PROG="generated/without_thforce.hex" sbt run > /dev/null

if [ ! -f "generated/filelist.f" ]; then
    echo "Error: No 'generated/filelist.f' found after build"
    exit 1
fi

cd generated
verilator --cc --exe --build --trace --quiet -f filelist.f ../sim.cpp --top-module Core

echo "--------- Without Thforce ---------"
obj_dir/VCore

# With Thforce

cd ..

riscv32-none-elf-as -march=rv32i -mabi=ilp32 examples/with_thforce.asm -o generated/with_thforce.o
riscv32-none-elf-ld -T link.ld generated/with_thforce.o -o generated/with_thforce.elf
riscv32-none-elf-objcopy -O verilog --verilog-data-width=4 generated/with_thforce.elf generated/with_thforce.hex

PROG="generated/with_thforce.hex" sbt run > /dev/null

if [ ! -f "generated/filelist.f" ]; then
   echo "Error: No 'generated/filelist.f' found after build"
   exit 1
fi

cd generated

verilator --cc --exe --build --trace --quiet -f filelist.f ../sim.cpp --top-module Core

echo "---------  With  Thforce  ---------"
obj_dir/VCore

# Cleanup the mess
if [ ! "$1" = "--keep" ]; then
    rm *.{elf,o,hex,vcd}
    rm -rf obj_dir
fi
